name: flutter_project_starter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # custom packages
  data:
    path: data/

  # annotation
  meta: any

  # utility
  intl: any
  collection: any
  async: any

  path: ^1.9.1
  path_provider: ^2.1.5
  platform_info: ^5.0.0
  device_info_plus: ^11.4.0
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.4
  permission_handler: ^12.0.0+1

  # networking
  dio_retry_plus: ^2.0.8
  thunder: ^0.1.0

  # routing
  go_router: ^15.1.2

  # state management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # firebase
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  firebase_messaging: ^15.2.6
  firebase_remote_config: ^5.4.4
  firebase_analytics: ^11.4.6

  # notifications
  flutter_local_notifications: ^19.2.1

  # UI and widgets
  shimmer: ^3.0.0
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1
  share_plus: ^11.0.0
  skeletonizer: ^2.0.1

  # database
  drift: ^2.26.1
  drift_flutter: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # linting
  flutter_lints: ^5.0.0

  # code generation
  build_runner: ^2.4.15
  pubspec_generator: ^4.2.2
  flutter_gen_runner: ^5.10.0
  # dart run flutter_launcher_icons -f flutter_launcher_icons.yaml
  flutter_launcher_icons: ^0.14.3
  # dart run flutter_native_splash:create --path=flutter_native_splash.yaml
  flutter_native_splash: ^2.4.6
  vector_graphics_compiler: ^1.1.17
  drift_dev: ^2.26.0

flutter:
  uses-material-design: true
